FROM debian:11@sha256:94a048ddf3567dcb55a630e4996194da8a872da21c6f887f2d498b04e2ec5384 AS BUILDER

RUN apt-get update -y &&\
  apt-get install --force-yes -y build-essential libz-dev zlib1g-dev curl tree

ARG RESULT_LIB="/musl"

RUN uname -a && tree /usr/lib/gcc
RUN mkdir ${RESULT_LIB} && \
    curl -L -o musl.tar.gz https://more.musl.cc/10.2.1/x86_64-linux-musl/aarch64-linux-musl-native.tgz && \
    tar -xvzf musl.tar.gz -C musl --strip-components 1 && \
    cp /usr/lib/gcc/aarch64-linux-gnu/10/libstdc++.a ${RESULT_LIB}/lib/

ENV CC=/musl/bin/gcc

RUN curl -L -o zlib.tar.gz https://www.zlib.net/fossils/zlib-1.2.11.tar.gz && \
    mkdir zlib && tar -xvzf zlib.tar.gz -C zlib --strip-components 1 && \
    cd zlib && ./configure --static --prefix=/musl && \
    make && make install && \
    cd / && rm -rf /zlib && rm -f /zlib.tar.gz

ENV PATH="$PATH:/musl/bin"


ENV GRAALVM_URL='https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-aarch64_bin.tar.gz'
RUN mkdir /graalvm &&\
  curl -L $GRAALVM_URL > /tmp/graalvm.tgz &&\
  tar --strip 1 -zxvf /tmp/graalvm.tgz -C /graalvm &&\
  rm -r /tmp/* || true

ENV JAVA_HOME=/graalvm
ENV PATH="${PATH}:$JAVA_HOME/bin"
RUN uname -a && whoami && ls -lha $JAVA_HOME/bin && $JAVA_HOME/bin/java -version

COPY ./ /app
WORKDIR /app

RUN ./gradlew clean build compTest shadowJar nativeCompile -i &&\
  ls -lha ./build &&\
  mkdir -p ./build/artifacts/linux-amd64 && mv ./build/native/nativeCompile/dns-proxy-server ./build/artifacts/linux-amd64/ &&\
  mkdir -p ./build/artifacts/jre && mv ./build/libs/dns-proxy-server-*-all.jar ./build/artifacts/jre/dns-proxy-server.jar &&\
  mkdir -p ./build/artifacts/native-image-source && cp ./build/artifacts/jre/dns-proxy-server.jar ./build/artifacts/native-image-source/ &&\
  ls -lhS ./build/artifacts/*

ENTRYPOINT cat
